# Form implementation generated from reading ui file 'D:\ktlt_final\UILogin\Dangki.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(140, 20, 581, 501))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(170, -40, 261, 151))
        self.label.setObjectName("label")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPhone.setGeometry(QtCore.QRect(50, 170, 471, 51))
        self.lineEditPhone.setStyleSheet("color: rgb(143, 143, 143);")
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.pushButtonDangki = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonDangki.setGeometry(QtCore.QRect(190, 250, 201, 51))
        self.pushButtonDangki.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"")
        self.pushButtonDangki.setObjectName("pushButtonDangki")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(140, 310, 181, 41))
        self.label_2.setObjectName("label_2")
        self.pushButtonDangnhap = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonDangnhap.setGeometry(QtCore.QRect(310, 320, 93, 28))
        self.pushButtonDangnhap.setObjectName("pushButtonDangnhap")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#00007f;\">Tạo tài khoản </span></p></body></html>"))
        self.lineEditPhone.setText(_translate("MainWindow", "* Số điện thoại"))
        self.pushButtonDangki.setText(_translate("MainWindow", "Đăng ký"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Đã có tài khoản rồi ? </span></p></body></html>"))
        self.pushButtonDangnhap.setText(_translate("MainWindow", "Đăng nhập"))
