# Form implementation generated from reading ui file 'C:\Users\nguye\PycharmProjects\ktlt_final\UILogin\LoginEmployee.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1184, 992)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(280, 260, 471, 401))
        self.groupBox.setStyleSheet("background-color: rgb(239, 236, 212);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 120, 311, 241))
        self.groupBox_2.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButtonLoginEmployee = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonLoginEmployee.setGeometry(QtCore.QRect(90, 140, 121, 41))
        self.pushButtonLoginEmployee.setStyleSheet("background-color: rgb(117, 5, 68);\n"
"font: 63 13pt \"Sitka Small Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButtonLoginEmployee.setObjectName("pushButtonLoginEmployee")
        self.lineEditPasswordEmployee = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditPasswordEmployee.setGeometry(QtCore.QRect(70, 80, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(10)
        self.lineEditPasswordEmployee.setFont(font)
        self.lineEditPasswordEmployee.setStyleSheet("color: rgb(124, 124, 124);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditPasswordEmployee.setText("")
        self.lineEditPasswordEmployee.setObjectName("lineEditPasswordEmployee")
        self.lineEditUsernameEmployee = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditUsernameEmployee.setGeometry(QtCore.QRect(70, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(10)
        self.lineEditUsernameEmployee.setFont(font)
        self.lineEditUsernameEmployee.setStyleSheet("color: rgb(126, 126, 126);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditUsernameEmployee.setText("")
        self.lineEditUsernameEmployee.setObjectName("lineEditUsernameEmployee")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(130, 200, 21, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\\\Users\\\\nguye\\\\PycharmProjects\\\\ktlt_final\\\\images\\\\next.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 35, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\\\Users\\\\nguye\\\\PycharmProjects\\\\ktlt_final\\\\images\\\\user (1).png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 31, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\\\Users\\\\nguye\\\\PycharmProjects\\\\ktlt_final\\\\images\\\\padlock.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(190, 20, 91, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\\\Users\\\\nguye\\\\PycharmProjects\\\\ktlt_final\\\\images\\\\user.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButtonLoginEmployee.setText(_translate("MainWindow", "Log in"))
        self.lineEditPasswordEmployee.setPlaceholderText(_translate("MainWindow", "* Password"))
        self.lineEditUsernameEmployee.setPlaceholderText(_translate("MainWindow", "*User Name"))
