# Form implementation generated from reading ui file 'C:\Users\nguye\PycharmProjects\ktlt_final\UILogin\Signup.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 915)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(90, 20, 621, 641))
        self.groupBox.setStyleSheet("background-color: rgb(239, 236, 212);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 0, 621, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka Small Semibold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 54, 0);")
        self.label.setObjectName("label")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditUsername.setGeometry(QtCore.QRect(160, 130, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(11)
        self.lineEditUsername.setFont(font)
        self.lineEditUsername.setStyleSheet("color: rgb(143, 143, 143);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.pushButtonSignUp = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSignUp.setGeometry(QtCore.QRect(160, 490, 241, 51))
        self.pushButtonSignUp.setStyleSheet("background-color: rgb(117, 5, 68);\n"
"font: 63 13pt \"Sitka Small Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(230, 70, 61, 61))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 236, 212);")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("C:\\Users\\nguye\\PycharmProjects\\ktlt_final\\UILogin\\lotus_2982182 (1).png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.lineEditPass = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPass.setGeometry(QtCore.QRect(160, 200, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(11)
        self.lineEditPass.setFont(font)
        self.lineEditPass.setStyleSheet("color: rgb(143, 143, 143);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditPass.setObjectName("lineEditPass")
        self.lineEditPhoneNumber = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPhoneNumber.setGeometry(QtCore.QRect(160, 350, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(11)
        self.lineEditPhoneNumber.setFont(font)
        self.lineEditPhoneNumber.setStyleSheet("color: rgb(143, 143, 143);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditPhoneNumber.setObjectName("lineEditPhoneNumber")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditEmail.setGeometry(QtCore.QRect(160, 280, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(11)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setStyleSheet("color: rgb(143, 143, 143);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditYourName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditYourName.setGeometry(QtCore.QRect(160, 420, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(11)
        self.lineEditYourName.setFont(font)
        self.lineEditYourName.setStyleSheet("color: rgb(143, 143, 143);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditYourName.setObjectName("lineEditYourName")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonBack.setGeometry(QtCore.QRect(160, 560, 241, 51))
        self.pushButtonBack.setStyleSheet("background-color: rgb(117, 5, 68);\n"
"font: 63 13pt \"Sitka Small Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButtonBack.setObjectName("pushButtonBack")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#fffff2;\">Create account</span></p></body></html>"))
        self.lineEditUsername.setText(_translate("MainWindow", "* Username"))
        self.pushButtonSignUp.setText(_translate("MainWindow", "Sign in"))
        self.lineEditPass.setText(_translate("MainWindow", "* Pass"))
        self.lineEditPhoneNumber.setText(_translate("MainWindow", "* Phone Number"))
        self.lineEditEmail.setText(_translate("MainWindow", "* Email"))
        self.lineEditYourName.setText(_translate("MainWindow", "* Full Name"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back"))
