# Form implementation generated from reading ui file 'C:\Users\nguye\PycharmProjects\ktlt_final\UILogin\Signup.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 915)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 60, 661, 501))
        self.groupBox.setStyleSheet("background-color: rgb(239, 236, 212);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 0, 661, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka Small Semibold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 54, 0);")
        self.label.setObjectName("label")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(290, 70, 61, 61))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 236, 212);")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("C:/Users/ADMIN/AppData/Local/Temp/1baae3cc-5385-4d86-bc85-6bef75179ec4_ktlt_final.zip.ec4/ktlt_final/UILogin/lotus_2982182 (1).png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 119, 521, 321))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditUsername.setGeometry(QtCore.QRect(210, 10, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(11)
        self.lineEditUsername.setFont(font)
        self.lineEditUsername.setStyleSheet("color: rgb(143, 143, 143);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.lineEditPass = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditPass.setGeometry(QtCore.QRect(210, 60, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(11)
        self.lineEditPass.setFont(font)
        self.lineEditPass.setStyleSheet("color: rgb(143, 143, 143);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditPass.setObjectName("lineEditPass")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditEmail.setGeometry(QtCore.QRect(210, 110, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(11)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setStyleSheet("color: rgb(143, 143, 143);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditPhoneNumber = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditPhoneNumber.setGeometry(QtCore.QRect(210, 160, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(11)
        self.lineEditPhoneNumber.setFont(font)
        self.lineEditPhoneNumber.setStyleSheet("color: rgb(143, 143, 143);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditPhoneNumber.setObjectName("lineEditPhoneNumber")
        self.lineEditYourName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditYourName.setGeometry(QtCore.QRect(210, 210, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(11)
        self.lineEditYourName.setFont(font)
        self.lineEditYourName.setStyleSheet("color: rgb(143, 143, 143);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditYourName.setObjectName("lineEditYourName")
        self.pushButtonSignUp = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonSignUp.setGeometry(QtCore.QRect(220, 260, 121, 41))
        self.pushButtonSignUp.setStyleSheet("background-color: rgb(117, 5, 68);\n"
"font: 63 13pt \"Sitka Small Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonBack.setGeometry(QtCore.QRect(370, 260, 111, 41))
        self.pushButtonBack.setStyleSheet("background-color: rgb(117, 5, 68);\n"
"font: 63 13pt \"Sitka Small Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 191, 321))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\\\Users\\\\nguye\\\\PycharmProjects\\\\ktlt_final\\\\images\\\\CHAY_Menu-Alacarte_T5.2024-2.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(4, 140, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#fffff2;\">Create account</span></p></body></html>"))
        self.lineEditUsername.setText(_translate("MainWindow", "* Username"))
        self.lineEditPass.setText(_translate("MainWindow", "* Pass"))
        self.lineEditEmail.setText(_translate("MainWindow", "* Email"))
        self.lineEditPhoneNumber.setText(_translate("MainWindow", "* Phone Number"))
        self.lineEditYourName.setText(_translate("MainWindow", "* Full Name"))
        self.pushButtonSignUp.setText(_translate("MainWindow", "Sign in"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-style:italic; color:#828282;\">Create account </span></p></body></html>"))
