# Form implementation generated from reading ui file 'C:\Users\nguye\PycharmProjects\ktlt_final\UILogin\Signup.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 40, 541, 381))
        self.groupBox.setStyleSheet("background-color: rgb(239, 236, 212);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 0, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka Small Semibold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 54, 0);")
        self.label.setObjectName("label")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPhone.setGeometry(QtCore.QRect(30, 160, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(11)
        self.lineEditPhone.setFont(font)
        self.lineEditPhone.setStyleSheet("color: rgb(143, 143, 143);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.pushButtonDangki = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonDangki.setGeometry(QtCore.QRect(140, 240, 241, 51))
        self.pushButtonDangki.setStyleSheet("background-color: rgb(117, 5, 68);\n"
"font: 63 13pt \"Sitka Small Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButtonDangki.setObjectName("pushButtonDangki")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(140, 310, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButtonDangnhap = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonDangnhap.setGeometry(QtCore.QRect(290, 310, 93, 28))
        self.pushButtonDangnhap.setStyleSheet("background-color: rgb(117, 5, 68);\n"
"font: 63 10pt \"Sitka Small Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.pushButtonDangnhap.setObjectName("pushButtonDangnhap")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(230, 70, 61, 61))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 236, 212);")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("C:\\Users\\nguye\\PycharmProjects\\ktlt_final\\UILogin\\lotus_2982182 (1).png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#fffff2;\">Create account</span></p></body></html>"))
        self.lineEditPhone.setText(_translate("MainWindow", "* Phone number or Email"))
        self.pushButtonDangki.setText(_translate("MainWindow", "Sign in"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Already have an account?</span></p></body></html>"))
        self.pushButtonDangnhap.setText(_translate("MainWindow", "Log in"))
